# Generated by Django 5.2.15 on 2026-06-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_adi', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=40)),
                ('soyad', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('aciklama', models.CharField(max_length=200)),
                ('son_tarih', models.DateField()),
                ('ders_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odevler.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='deadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teslim_tarihi', models.DateTimeField(auto_now_add=True)),
                ('dosya', models.FileField(upload_to='teslimler/')),
                ('puan', models.IntegerField(blank=True, null=True)),
                ('sinav', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odevler.exam')),
                ('ogrenci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odevler.student')),
            ],
        ),
    ]
